### ISSUE TITLE
Posts with accents etc. in the url aren't generating fetched previews correctly

### ISSUE THREAD

**Issue by jhnhnsn** [johnmidgley/opencola-alpha#10]
**Describe the bug**
Users trying to post links with non-roman (probably?) characters are having problems. From Discord group:
- https://en.wikipedia.org/wiki/Bronisław_Huberman
- "I just tried with a wikipedia article of a persons whose name has an ë in it and it also didn't generate a preview"

**To Reproduce**
1. Post "https://en.wikipedia.org/wiki/Bronisław_Huberman" using the Description field
2. Click to "save"

**Expected behavior**
Expected a preview of the content on that wikipedia page

** Actual/observed behavior
Just a self-post with the copied url in the body

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11/Mac OS

**Additional context**
Worked fine when I used the sanitized version copied from the Discord report of the issue eg. https://en.wikipedia.org/wiki/Bronis%C5%82aw_Huberman. Seems like we might not be encoding non-roman characters correctly or something.

**Comment by johnmidgley** [comment]
I tried to repro both by adding the link with the toolbar and adding via the description, but both worked fine for me. @jhnhnsn Does this repro for you on Mac with the latest build?

**Comment by johnmidgley** [comment]
No repro.
