### ISSUE TITLE
Error when running 'start' script on macOS

### ISSUE THREAD

**Issue by mebibite** [johnmidgley/opencola-alpha#2]
**Describe the bug**
I receive an 'hostname: illegal option -- I' error when running the 'linux/start' script:

tomas :: docker/opencola/linux » ./start
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
Creating storage
No SSL certificate found

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 ⠿ Network opencola_default   Created 0.1s
 ⠿ Container opencola-server  Started 1.0ss
Docker container started
Waiting for certificate creation
New certs have been created. Install (y/n)?
y
~/.opencola/storage/cert ~/docker/opencola/linux
Password:
~/docker/opencola/linux
Server started

Insecure URLS:
http://localhost:5795 (Local only)
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]

Secure URLs (Recommended):
https://localhost:5796 (Local only)
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]

**Comment by johnmidgley** [comment]
Looks like you're running the Linux start command on a Mac. I created separate Mac and Linux folders, as there are now specialized commands. Can you try the start script in the Mac directory?

**Comment by mebibite** [comment]
Old habits die hard. Completely missed that, sorry.

This works correctly:

tomas :: docker/opencola/mac » ./start
Creating storage
No SSL certificate found

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 ⠿ Network opencola_default   Created 0.1s
 ⠿ Container opencola-server  Started 0.6ss
Docker container started
Waiting for certificate creation
New certs have been created. Install (y/n)?
y
~/.opencola/storage/cert ~/docker/opencola/mac
Password:
~/docker/opencola/mac
Server started

Insecure URLS:
http://localhost:5795 (Local only)
http://192.168.1.39:5795
http://10.243.170.198:5795

Secure URLs (Recommended):
https://localhost:5796 (Local only)
https://192.168.1.39:5796
https://10.243.170.198:5796
