### ISSUE TITLE
Extension thinks server is running, when it isn't

### ISSUE THREAD

**Issue by jeanlucaslima** [johnmidgley/opencola-alpha#3]
Server not running, but extension thinks it is. 

1. Install OpenCola
2. Run for the first time, install everything
3. Restart machine
4. Start browser without starting the docker image

**Expected behavior**
It should not give a green light for status. 

**Screenshots**
<img width="280" alt="image" src="https://user-images.githubusercontent.com/1311402/204293926-af90e8e7-5b1b-4247-8a59-5e9e6568077f.png">

**Desktop**
 - OS: MacOS 13.0.1
 - Browser Chrome
 - Version 107.0.5304.110 (Official Build) (x86_64)

**Comment by johnmidgley** [comment]
Thanks for the report. I've added a fix that checks that the server is running and pops up a dialog letting the user know if it's not running. I'll get this deployed soon - just working on simplifying the install.

**Comment by johnmidgley** [comment]
Fixed in the 1.1.5 release.
