### ISSUE TITLE
 Server doesn't run despite saying it's running

### ISSUE THREAD

**Issue by BekaValentine** [johnmidgley/opencola-alpha#5]
**Describe the bug**

After running the `./start` script on Linux, it says it's waiting for certs, then displays URLs, and then exists. None of the URLs are working, there is no mention of installing certs.

**To Reproduce**

`./start`

**Expected behavior**

Probably should ask to install the certs. Server should stay on if its not. Clicking the links should open *something*.

**Comment by johnmidgley** [comment]
Seems like something isn't happening right inside docker. Can you edit the start script and change

```
docker-compose -p opencola up --build -d 1>/dev/null
```

to

```
docker-compose -p opencola up --build 
```

This will let the docker output go right to your terminal. You should see an error in there that will help debug.

**Comment by johnmidgley** [comment]
The install has been revamped in 1.1.5, and this was fixed.
