### ISSUE TITLE
Linux start-up instructions fails to mention use of sudo; but, it seems to be required on Pop_OS.

### ISSUE THREAD

**Issue by sam-falvo** [johnmidgley/opencola-alpha#6]
**Describe the bug**
Linux start-up instructions fails to mention use of sudo or that services should be run from root; but, it seems to be required on Pop_OS.

**To Reproduce**
1. Install docker-compose on Pop_OS! using `sudo apt install docker docker-compose`.
2. Follow, to the letter, the installation instructions for OpenCola.ai.

Observe a long list of Python exception traces, the first of which indicates a permission error when attempting to open a socket.

**NOTE:** I am not fluent with either Docker or Docker-Compose.  This may be an issue with the latter and not with OpenCola itself.

**Expected behavior**
The behavior expected is already detailed in the project's README.md file.

**Desktop (please complete the following information):**
 - OS: Pop_OS!
 - Browser Firefox 104.0.2 (64-bit) for Linux

Thanks!

**Comment by johnmidgley** [comment]
Thanks for the report. Linux is super challenging with so many variants, it's hard to know what's needed where. Just to be clear, were you able to get things to running with `sudo ./start`?

**Comment by sam-falvo** [comment]
It seems like I have, yes.  :)  I just wasn't sure if I was doing something wrong/untrustworthy/dangerous by running it as root or if omitting sudo was an oversight in the documentation.  I thought I would open this issue in the hopes I could maybe get that answered by someone smarter than me in such matters.  :)

**Comment by virtadpt** [comment]
I was going to say, I'm running it as an unprivileged user without any trouble.

Maybe there's a `docker` group that you have to add your account to so you don't need elevated privileges?

**Comment by sam-falvo** [comment]
@virtadpt , @mebibite -- thanks for the extra set of eyes.  I will look at my settings and make adjustments accordingly.  If it works out, I'll close this issue.

**Comment by johnmidgley** [comment]
I will close this for now. In version 1.1.5 you can now install on linux without docker. The docker install is still available, so if there's something that needs to be addressed, please re-open.
