### ISSUE TITLE
Comments Disappear Over 3

### ISSUE THREAD

**Issue by kynda** [johnmidgley/opencola-alpha#7]
**Describe the bug**
When commenting on a post, after 4 comments have been added, the oldest comment disappears from the UI.

**To Reproduce**

1. Add a new post in Open Cola
2. Add a comment on the post
3. Add a second, third and forth comment on the post

The comment in 2 will no longer appear.

**Expected behavior**
All comments on the post would appear.

**Desktop (please complete the following information):**
 - OS: POP_OS
 - Browser Librewolf
 - Version 107.0.1

**Comment by johnmidgley** [comment]
Thanks for the suggestion!

**Comment by johnmidgley** [comment]
This has been fixed in 1.1.6.
